os:
  - osx
  - linux

sudo: false

language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.20"
  - "5.18"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://install.perlbrew.pl | bash ; source $HOME/perl5/perlbrew/etc/bashrc; perlbrew install -j4 --notest --as perl-$TRAVIS_PERL_VERSION $(perlbrew available | grep $TRAVIS_PERL_VERSION | cut -c4- | head -1); perlbrew clean; perlbrew install-cpanm; perlbrew use "$TRAVIS_PERL_VERSION"; fi
  - perlbrew --version
  - cpanm --version
  - perl --version
  - cpanm --notest List::Util~1.50 Test2::Harness

script:
  yath --qvf

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true
