sudo: false

language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.20"
  - "5.18"

before_install:
  - cpanm --notest Test2::Harness

script:
  yath --qvf

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true
