---
abstract: 'change-suggester about insignificant details.'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  Test2::Harness: '0'
  Test2::V0: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.041, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-PerlNitpick
provides:
  App::PerlNitpick:
    file: lib/App/PerlNitpick.pm
    version: v0.4.0
  App::PerlNitpick::Nitpicker:
    file: lib/App/PerlNitpick/Nitpicker.pm
  App::PerlNitpick::PCPWrap:
    file: lib/App/PerlNitpick/PCPWrap.pm
  App::PerlNitpick::Rule::AddTrailingCommas:
    file: lib/App/PerlNitpick/Rule/AddTrailingCommas.pm
  App::PerlNitpick::Rule::AppendUnimportStatement:
    file: lib/App/PerlNitpick/Rule/AppendUnimportStatement.pm
  App::PerlNitpick::Rule::DedupeIncludeStatements:
    file: lib/App/PerlNitpick/Rule/DedupeIncludeStatements.pm
  App::PerlNitpick::Rule::QuoteSimpleStringWithSingleQuote:
    file: lib/App/PerlNitpick/Rule/QuoteSimpleStringWithSingleQuote.pm
  App::PerlNitpick::Rule::RemoveEffectlessUTF8Pragma:
    file: lib/App/PerlNitpick/Rule/RemoveEffectlessUTF8Pragma.pm
  App::PerlNitpick::Rule::RemoveTrailingWhitespace:
    file: lib/App/PerlNitpick/Rule/RemoveTrailingWhitespace.pm
  App::PerlNitpick::Rule::RemoveUnnecessaryScalarKeyword:
    file: lib/App/PerlNitpick/Rule/RemoveUnnecessaryScalarKeyword.pm
  App::PerlNitpick::Rule::RemoveUnusedImport:
    file: lib/App/PerlNitpick/Rule/RemoveUnusedImport.pm
  App::PerlNitpick::Rule::RemoveUnusedInclude:
    file: lib/App/PerlNitpick/Rule/RemoveUnusedInclude.pm
  App::PerlNitpick::Rule::RemoveUnusedVariables:
    file: lib/App/PerlNitpick/Rule/RemoveUnusedVariables.pm
  App::PerlNitpick::Rule::RewriteHeredocAsQuotedString:
    file: lib/App/PerlNitpick/Rule/RewriteHeredocAsQuotedString.pm
  App::PerlNitpick::Rule::RewriteWithAssignmentOperators:
    file: lib/App/PerlNitpick/Rule/RewriteWithAssignmentOperators.pm
requires:
  Getopt::Long: '0'
  Module::Find: '0'
  Moose: '0'
  Object::Method: '0'
  PPI: '0'
  PPIx::Utils: '0'
  Perl::Critic: '0'
  Perl::Critic::TooMuchCode: '0'
  String::PerlQuote: '0'
resources:
  bugtracker: https://github.com/gugod/App-PerlNitpick/issues
  homepage: https://github.com/gugod/App-PerlNitpick
  repository: git://github.com/gugod/App-PerlNitpick.git
version: v0.4.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_spdx_expression: MIT
x_static_install: '1'
