#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Long qw(GetOptions);
use Perl::Critic::Utils qw(all_perl_files);
use App::PerlNitpick;
use App::PerlNitpick::Nitpicker;

unshift @ARGV, split ' ', $ENV{PERL_NITPICK_OPTS} || '';

my %args;
GetOptions(
    \%args,
    "l|list",
    "r|rules=s",
    "i|inplace",
);

if ($args{l}) {
    App::PerlNitpick::Nitpicker->list_rules;
} elsif ($args{r}) {
    my @rules = split /\s*,\s*/, $args{r};
    for my $file (all_perl_files(@ARGV)) {
        my $x = App::PerlNitpick::Nitpicker->new(
            file => $file,
            rules => \@rules,
            inplace => ($args{i} ? 1 : 0),
        );
        $x->rewrite;
    }
}
